name: Build app

on: [push, pull_request]
jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: recursive

    - name: Build
      run: |
        make -j$(nproc)

    - name: Deploy
      if: ${{ github.event_name != 'pull_request' && github.event.action != 'unassigned' }}
      uses: actions/upload-artifact@master
      with:
        name: ${{ github.event.repository.name }}
        path: ./*.nro
